language: objective-c
osx_image: xcode7.3

env:
  global:
  - PROJECT=AvatarImageView
  - SCHEME=$PROJECT
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"
    
script: 
  - xctool clean test -project "$PROJECT.xcodeproj" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION"

branches:
  only:
  - master
  - develop