language: objective-c
osx_image: xcode7.3

env:
  global:
  - PROJECT=AvatarImageView
  - SCHEME=$PROJECT
  matrix:
    - DESTINATION="name=iPhone 6s"

script: 
  - xctool clean test -project "$PROJECT.xcodeproj" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION"

branches:
  only:
  - master
  - develop